---
- job:
    name: k8s-capi-images-build
    parent: base
    pre-run: playbooks/pre.yml
    run: playbooks/build.yml
    required-projects:
      - kubernetes-sigs/image-builder

- project:
    merge-mode: squash-merge
    default-branch: main
    check:
      jobs:
        - k8s-capi-images-build
        - yamllint
        - flake8
    gate:
      jobs:
        - yamllint
        - flake8
