---
- name: Build image
  hosts: all

  vars:
    distro: ubuntu
    distro_version: "2204"
    kubernetes_version: "124"
    repo_path: "{{ ansible_user_dir }}/src/github.com"
    upload_image: false

  tasks:
    - name: Run build script
      ansible.builtin.shell:
        executable: /bin/bash
        chdir: "{{ repo_path }}/kubernetes-sigs/image-builder/images/capi"
        cmd: |
          set -e
          set -x

          export PACKER_VAR_FILES={{ repo_path }}/osism/k8s-capi-images/extra_vars_openstack_{{ distro }}_{{ kubernetes_version }}.json
          export PATH=/home/zuul/.local/bin:$PATH

          make build-qemu-{{ distro }}-{{ distro_version }}
