---
- name: Build image
  hosts: all

  vars:
    distro: "{{ lookup('ansible.builtin.env', 'DISTRO', default='ubuntu') }}"
    distro_version: "{{ lookup('ansible.builtin.env', 'DISTRO_VERSION', default='2204') }}"
    extra_vars_openstack_directory: "{{ repo_path }}/osism/k8s-capi-images"
    kubernetes_version: "{{ lookup('ansible.builtin.env', 'KUBERNETES_VERSION', default='124') }}"
    repo_path: "{{ ansible_user_dir|default('~') }}/src/github.com"
    working_directory: "{{ repo_path }}/kubernetes-sigs/image-builder/images/capi"

  tasks:
    - name: Run build script
      ansible.builtin.shell:
        executable: /bin/bash
        chdir: "{{ working_directory }}"
        cmd: |
          set -e
          set -x

          export PACKER_VAR_FILES={{ extra_vars_openstack_directory }}/extra_vars_openstack_{{ distro }}_{{ kubernetes_version }}.json
          export PATH=~/.local/bin:$PATH

          make build-qemu-{{ distro }}-{{ distro_version }}
