---
- name: Build image
  hosts: all
  connection: local

  vars:
    basepath: "{{ ansible_user_dir }}/src/github.com"
    working_directory: "{{ basepath }}/kubernetes-sigs/image-builder/images/capi"

    distro: ubuntu
    distro_version: 2204

  tasks:
    - name: Run build script
      ansible.builtin.shell:
        executable: /bin/bash
        chdir: "{{ working_directory }}"
        cmd: |
          set -e
          set -x

          pwd
          ls -la

          export PACKER_VAR_FILES={{ basepath }}/osism/k8s-capi-images/extra_vars_{{ kubernetes_version }}.json
          export PATH=~/.local/bin:$PATH

          make build-qemu-{{ distro }}-{{ distro_version }}
