---
- name: Pre play
  hosts: all

  vars:
    ppg_version: "3.1.4"
    packer_version: "1.8.6"

    working_directory: "{{ zuul.project.src_dir|default('~') }}"

  tasks:
    - name: Install required packages
      become: true
      ansible.builtin.apt:
        name:
          - curl
          - git
          - jq
          - libguestfs-tools
          - make
          - patch
          - python3-pip
          - qemu-kvm
          - software-properties-common
          - unzip
        update_cache: true

    - name: Install packer
      ansible.builtin.include_role:
        name: ensure-packer

    - name: Install pip
      ansible.builtin.include_role:
        name: ensure-pip

    - name: Run install script
      ansible.builtin.shell:
        executable: /bin/bash
        cmd: |
          set -e
          set -x

          while fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 5; done;
          while fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do sleep 5; done;

          sudo apt-get update
          sudo apt-get install -y \
              curl \
              git \
              jq \
              libguestfs-tools \
              make \
              patch \
              python3-pip \
              qemu-kvm \
              software-properties-common \
              unzip

          sudo pip3 install ansible

          sudo chmod 0777 /dev/kvm

          echo "Host *" | sudo tee /etc/ssh/ssh_config
          echo "    PubkeyAcceptedAlgorithms +ssh-rsa" | sudo tee /etc/ssh/ssh_config
          echo "    HostkeyAlgorithms +ssh-rsa" | sudo tee /etc/ssh/ssh_config

          wget \
              -O packer-provisioner-goss.zip \
              https://github.com/YaleUniversity/packer-provisioner-goss/releases/download/v{{ ppg_version }}/packer-provisioner-goss-v{{ ppg_version }}-linux-amd64.zip
          unzip packer-provisioner-goss.zip -d /tmp
          mkdir -p ~/.packer.d/plugins
          mv /tmp/packer-provisioner-goss ~/.packer.d/plugins
