---
- name: Pre tasks - part 1
  hosts: all

  vars:
    working_directory: "{{ zuul.project.src_dir|default('~') }}"

  tasks:
    - name: Run install script
      ansible.builtin.shell:
        executable: /bin/bash
        chdir: "{{ working_directory }}"
        cmd: |
          set -e
          set -x

          while fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 5; done;
          while fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do sleep 5; done;

          sudo apt-get update
          sudo apt-get install -y \
              curl \
              git \
              jq \
              make \
              patch \
              python3-pip \
              qemu-kvm \
              software-properties-common \
              unzip

          sudo apt-add-repository --yes --update ppa:ansible/ansible
          sudo apt-get install -y ansible

          sudo chmod 0777 /dev/kvm

          echo "Host *" | sudo tee /etc/ssh/ssh_config
          echo "    PubkeyAcceptedAlgorithms +ssh-rsa" | sudo tee /etc/ssh/ssh_config
          echo "    HostkeyAlgorithms +ssh-rsa" | sudo tee /etc/ssh/ssh_config

          lsmod


- name: Pre roles
  hosts: all

  vars:
    install_packer: false
    install_pip: false

  roles:
    - role: ensure-packer
      vars:
        packer_version: "1.8.6"
      when: install_packer|bool

    - role: ensure-pip
      when: install_pip|bool

- name: Pre tasks - part 2
  hosts: all

  vars:
    packer_provisioner_goss_version: "3.1.4"
    working_directory: "{{ zuul.project.src_dir|default('~') }}"

  tasks:
    - name: Run install script
      ansible.builtin.shell:
        executable: /bin/bash
        chdir: "{{ working_directory }}"
        cmd: |
          set -e
          set -x

          wget -O packer-provisioner-goss.zip https://github.com/YaleUniversity/packer-provisioner-goss/releases/download/v{{ packer_provisioner_goss_version }}/packer-provisioner-goss-v{{ packer_provisioner_goss_version }}-linux-amd64.zip
          unzip packer-provisioner-goss.zip -d /tmp
          mkdir -p ~/.packer.d/plugins
          mv /tmp/packer-provisioner-goss ~/.packer.d/plugins
